backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "hujan"
    label: "Update Data Hujan"
    folder: "data/hujan"
    create: true
    slug: "{{year}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "Tahun", name: "year", widget: "string" }
      - { label: "Pesanggrahan", name: "st_01", widget: "number", value_type: "float" }
      - { label: "Angke", name: "st_02", widget: "number", value_type: "float" }
      - { label: "Krukut", name: "st_03", widget: "number", value_type: "float" }
      - { label: "Keterangan Tambahan", name: "body", widget: "text", required: false }
